# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import poeg.apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('slider_content', models.TextField(blank=True, verbose_name='slider content')),
                ('image', models.ImageField(blank=True, null=True, upload_to=poeg.apps.core.models.slider_image_upload_to, verbose_name='image')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this slide is active.', verbose_name='active')),
                ('homepageorder', models.PositiveSmallIntegerField(blank=True, help_text='Order on homepage', null=True, unique=True, verbose_name='homepageorder')),
            ],
            options={
                'ordering': ('homepageorder',),
            },
        ),
    ]
