# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('homepageblock', models.TextField(blank=True, verbose_name='homepageblock')),
                ('modalblock', models.TextField(blank=True, verbose_name='modalblock')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this game is active.', verbose_name='active')),
                ('homepageorder', models.PositiveSmallIntegerField(blank=True, help_text='Order on homepage', null=True, unique=True, verbose_name='homepageorder')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='hint')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hints/', verbose_name='image')),
                ('time_penalty', models.PositiveIntegerField(default=0, verbose_name='penalty')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order withing quest')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order withing game')),
                ('description', models.TextField(blank=True, verbose_name='quest description')),
                ('jscode', models.TextField(blank=True, verbose_name='javascript code')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Game', verbose_name='gameid')),
            ],
        ),
        migrations.AddField(
            model_name='hint',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Quest', verbose_name='quest'),
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=set([('game', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together=set([('quest', 'order')]),
        ),
    ]
