# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170519_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finishpage',
            field=models.TextField(blank=True, verbose_name='finishpage'),
        ),
        migrations.AddField(
            model_name='game',
            name='startpage',
            field=models.TextField(blank=True, verbose_name='startpage'),
        ),
    ]
