# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20170520_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='after_quest',
            field=models.TextField(blank=True, verbose_name='text between quests'),
        ),
    ]
