# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def transl_upgrade(apps, schema_editor):
    Game = apps.get_model('games.Game')
    GameTranslation = apps.get_model('games.GameTranslation')
    for game in Game.objects.all():
        gt = GameTranslation.objects.create(
            master_id=game.id,
            language_code='cs',
            name=game.name,
            homepageblock=game.homepageblock,
            modalblock=game.modalblock,
            startpage=game.startpage,
            finishpage=game.finishpage
        )
        print('Translation for game id %s created' % game.id)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170609_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('homepageblock', models.TextField(blank=True, verbose_name='homepageblock')),
                ('modalblock', models.TextField(blank=True, verbose_name='modalblock')),
                ('startpage', models.TextField(blank=True, verbose_name='startpage')),
                ('finishpage', models.TextField(blank=True, verbose_name='finishpage')),
            ],
            options={
                'verbose_name': 'game Translation',
                'db_table': 'games_game_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='gametranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='games.Game'),
        ),
        migrations.AlterUniqueTogether(
            name='gametranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.RunPython(
            code=transl_upgrade,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='game',
            name='finishpage',
        ),
        migrations.RemoveField(
            model_name='game',
            name='homepageblock',
        ),
        migrations.RemoveField(
            model_name='game',
            name='modalblock',
        ),
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='startpage',
        ),
    ]
