# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def transl_upgrade(apps, schema_editor):
    Quest = apps.get_model('games.Quest')
    QuestTranslation = apps.get_model('games.QuestTranslation')
    for one in Quest.objects.all():
        gt = QuestTranslation.objects.create(
            master_id=one.id,
            language_code='cs',
            description=one.description,
            jscode=one.jscode,
            after_quest=one.after_quest,
        )
        print('Translation for quest id %s created' % one.id)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20170615_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.TextField(blank=True, verbose_name='quest description')),
                ('jscode', models.TextField(blank=True, verbose_name='javascript code')),
                ('after_quest', models.TextField(blank=True, verbose_name='text between quests')),
            ],
            options={
                'verbose_name': 'quest Translation',
                'db_table': 'games_quest_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='questtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='games.Quest'),
        ),
        migrations.AlterUniqueTogether(
            name='questtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.RunPython(
            code=transl_upgrade,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='quest',
            name='after_quest',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='jscode',
        ),
    ]
