# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def transl_upgrade(apps, schema_editor):
    Hint = apps.get_model('games.Hint')
    HintTranslation = apps.get_model('games.HintTranslation')
    for one in Hint.objects.all():
        gt = HintTranslation.objects.create(
            master_id=one.id,
            language_code='cs',
            text=one.text,
        )
        print('\nTranslation for hint id %s created' % one.id)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20170615_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text', models.TextField(blank=True, verbose_name='hint')),
            ],
            options={
                'verbose_name': 'hint Translation',
                'db_table': 'games_hint_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='hinttranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='games.Hint'),
        ),
        migrations.AlterUniqueTogether(
            name='hinttranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.RunPython(
            code=transl_upgrade,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='hint',
            name='text',
        ),
    ]
