# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20170615_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegame',
            name='activation_type',
            field=models.CharField(blank=True, choices=[('gratis_martin', 'gratis Martin'), ('gratis_lucka', 'gratis Lucka'), ('voucher_own', 'voucher own'), ('voucher_slevomat', 'voucher Slevomat'), ('bankwire', 'platba převodem'), ('gopay', 'platba GoPay')], max_length=50, verbose_name='activation type'),
        ),
    ]
