# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170523_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(blank=True, choices=[('cs', 'Czech'), ('en', 'English')], help_text='Language ISO.', max_length=5, verbose_name='prefered lang'),
        ),
    ]
