# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_quest_after_quest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlevomatAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slevomataction',
            unique_together=set([('game', 'product_id')]),
        ),
    ]
