# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_quest_after_quest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.SmallIntegerField(blank=True, choices=[(10, 'Slevomat'), (20, 'Bank transfer')], verbose_name='payment type')),
                ('variable', models.CharField(blank=True, max_length=20, unique=True, verbose_name='variable')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('ts_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='time of creation')),
                ('instruction_email_sent', models.BooleanField(db_index=True, default=False, verbose_name='payment instruction email sent')),
                ('notifications_send', models.SmallIntegerField(default=0, verbose_name='number of sent notifications')),
                ('ts_paid', models.DateTimeField(db_index=True, null=True, verbose_name='time of payment')),
                ('due_days', models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='Days of payment due')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='note')),
                ('user_email', models.EmailField(max_length=150, verbose_name='user email')),
                ('game_name', models.CharField(max_length=50, verbose_name='game name')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Game', verbose_name='gameid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
    ]
