# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170601_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Slevomat'), (20, 'Bank transfer')], default=20, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='ts_paid',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='time of payment'),
        ),
    ]
