# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='target_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, verbose_name='target price'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher',
            field=models.CharField(max_length=20, unique=True, verbose_name='voucher code'),
        ),
    ]
