# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20170606_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='GopayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'GoPay log entry',
                'verbose_name_plural': 'GoPay log entries',
                'ordering': ('-ts',),
            },
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_type',
            field=models.SmallIntegerField(blank=True, choices=[(10, 'Slevomat'), (20, 'Bank transfer'), (30, 'Gopay payment')], default=20, verbose_name='payment type'),
        ),
        migrations.AddField(
            model_name='gopaylog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.PaymentTransaction'),
        ),
    ]
