# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_voucher_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='given',
            field=models.BooleanField(default=False, verbose_name='given to customer'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
